create table tb_user (id int8 generated by default as identity, primary key (id), name varchar(255), email varchar(255), password varchar(511));
create table tb_role (id int8 generated by default as identity, primary key (id), name varchar(255));
create table tb_user_role (primary key (user_id, role_id), user_id int8, role_id int8);
